config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    collection do
      get :list
    end
  end
  resources :sessions, only: %i(create destroy)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #def current_user
  #  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #end

  #helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user_id = User.find(params[:user]).id
    cookies.signed[:user_id] = {
      value: user_id,
      expires: 1.day.from_now
    }
    redirect_to :back
  end

  def destroy
    cookies.signed[:user_id] = nil
    redirect_to :back
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.limit(5)
  end

  def list
    render json: Subject.limit(5).offset(5).to_json
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        broadcast
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        broadcast
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    broadcast
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def broadcast
    data = @subject.as_json.merge(action: params[:action])
    ActionCable.server.broadcast 'subject_channel', data
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleActioncable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subjects/_form.html.erb
<%= form_for(subject) do |f| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<dl id="subject_<%= subject.id %>">
  <dt><%= subject.name %></dt>
  <dd><%= subject.body %></dd>
  <dd>
    <%= link_to 'Edit', subject_path(subject) %>
    <%= link_to 'Delete', subject_path(subject), method: :delete, data: {confirm: 'A u sure?'} %>
  </dd>
</dl>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<%= form_tag '/sessions', method: :post do  %>
  <%= select_tag 'user', options_from_collection_for_select(User.all, "id", "name") %>
  <%= submit_tag 'ログイン' %>
<% end %>

<%= form_tag session_path(1), method: :delete do  %>
  <%= submit_tag 'ログアウト' %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<dl id='subjects'>
  <%= render @subjects %>
</dl>

<button type='button' id='list'>リストを取得</button>

<br>

<%= link_to 'New Subject', new_subject_path %>

<script>
  $(function(){
    $('#list').click(function () {
      $.getJSON('/subjects/list', function( data ) {
        var items = [];
        $.each( data, function( key, val ) {
          items.push( "<dl id='subject_" + val['id'] + "'><dt>" + val['name'] + "</dt><dd>" + val['body'] + "</dd><dd><a href='/subjects/" + val['id'] +"'>Edit</a><a data-confirm='A u sure?' rel='nofollow' data-method='delete' href='/subjects/" +val['id']+ "'>Delete</a></dd></dl>" );
        });

        $("dl#subjects").append(items.join( "" ));
      });
    });
  });
</script>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @subject.body %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>